package com.example.unibeyond.ui.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Brush

//-Gradient color scheme-
//First the serperate colors
val UniBeyondBlue = Color(0xFF4E44F8)
val UniBeyondPurple = Color(0xFFA63AF5)
//Secondly the gradient
val UniBeyondGradient = Brush.horizontalGradient(
    colors = listOf(UniBeyondBlue, UniBeyondPurple)
)

val primaryLight = Color(0xFF7B4E80)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFD5FF)
val onPrimaryContainerLight = Color(0xFF613767)
val secondaryLight = Color(0xFF6B586B)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFF4DBF2)
val onSecondaryContainerLight = Color(0xFF524153)
val tertiaryLight = Color(0xFF615690)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFE6DEFF)
val onTertiaryContainerLight = Color(0xFF493E76)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFFF7FA)
val onBackgroundLight = Color(0xFF1F1A1F)
val surfaceLight = Color(0xFFFFF7FB)
val onSurfaceLight = Color(0xFF1F1A1F)
val surfaceVariantLight = Color(0xFFECDFE9)
val onSurfaceVariantLight = Color(0xFF4D444C)
val outlineLight = Color(0xFF7E747D)
val outlineVariantLight = Color(0xFFD0C3CC)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF342F34)
val inverseOnSurfaceLight = Color(0xFFF8EEF5)
val inversePrimaryLight = Color(0xFFEAB5ED)
val surfaceDimLight = Color(0xFFE1D7DE)
val surfaceBrightLight = Color(0xFFFFF7FB)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFBF1F8)
val surfaceContainerLight = Color(0xFFF5EBF2)
val surfaceContainerHighLight = Color(0xFFEFE5ED)
val surfaceContainerHighestLight = Color(0xFFEAE0E7)



val primaryDark = Color(0xFFEAB5ED)
val onPrimaryDark = Color(0xFF48204F)
val primaryContainerDark = Color(0xFF613767)
val onPrimaryContainerDark = Color(0xFFFFD5FF)
val secondaryDark = Color(0xFFD7BFD5)
val onSecondaryDark = Color(0xFF3B2B3C)
val secondaryContainerDark = Color(0xFF524153)
val onSecondaryContainerDark = Color(0xFFF4DBF2)
val tertiaryDark = Color(0xFFCBBEFF)
val onTertiaryDark = Color(0xFF32285E)
val tertiaryContainerDark = Color(0xFF493E76)
val onTertiaryContainerDark = Color(0xFFE6DEFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF171217)
val onBackgroundDark = Color(0xFFEADFE6)
val surfaceDark = Color(0xFF161217)
val onSurfaceDark = Color(0xFFEAE0E7)
val surfaceVariantDark = Color(0xFF4D444C)
val onSurfaceVariantDark = Color(0xFFD0C3CC)
val outlineDark = Color(0xFF998D96)
val outlineVariantDark = Color(0xFF4D444C)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFEAE0E7)
val inverseOnSurfaceDark = Color(0xFF342F34)
val inversePrimaryDark = Color(0xFF7B4E80)
val surfaceDimDark = Color(0xFF161217)
val surfaceBrightDark = Color(0xFF3D373D)
val surfaceContainerLowestDark = Color(0xFF110D12)
val surfaceContainerLowDark = Color(0xFF1F1A1F)
val surfaceContainerDark = Color(0xFF231E23)
val surfaceContainerHighDark = Color(0xFF2D282E)
val surfaceContainerHighestDark = Color(0xFF393339)



